services:
  - type: web
    name: cardano-aquarium
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: BLOCKFROST_API_KEY
        sync: false  # Set this manually in Render dashboard